# Copyright (c) 2019 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lissio
  labels:
    app: lissio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lissio
  template:
    metadata:
      labels:
        app: lissio
    spec:
      containers:
      - name: lissio
        image: lissio
        command: ["/lissio"]
        args: ["-v", "--kubeconfig", "/kube/dev-dash-kubeconfig.yaml"]
        ports:
        - containerPort: 7777
        env:
          - name: LISSIO_LISTENER_ADDR
            value: 0.0.0.0:7777
          - name: LISSIO_DISABLE_OPEN_BROWSER
            value: "1"
        volumeMounts:
          - name: kubeconfig
            mountPath: /kube/
      volumes:
        - name: kubeconfig
          secret:
            secretName: lissio-kubeconfig
            defaultMode: 256
